### PR TITLE
Added Login_screen

### PR DESCRIPTION
**Pull request by krish-bhanushali**
I have added the login UI according to the wireframe. It would be great if you check it.

### CODE REVIEW

**Comment by krish-bhanushali** [comment]
Good ?

**Review by neil-dev — CHANGES_REQUESTED** [review]
In the login screen file, make the following changes:

- [x] Change the background color to #1a1a1a.
- [x] Change the uri of the logo to 'assets/logo.png'
- [x] Change the text of the button to 'Sign In'.
- [x] Remove the extra line after the Sign In button, it's not needed.
- [x] Change the keyboard in the text field from number to phone.
- [ ] Change the font size of the button text to 16.

**Comment by krish-bhanushali** [comment]
Done

**Review by neil-dev — APPROVED** [review]
Changes accepted

**Pull request merged**
