### PR TITLE
Added UI Design for App

### PR DESCRIPTION
**Pull request by malakar-swastik**
Added the UI Design for App. However, since no logo was available, I have used a default placeholder .

### CODE REVIEW

**Comment by Anushka-shukla** [comment]
Hi @malakar-swastik I would request some changes  
- Kindly remove the readme file from the UI Design Drafts folder as we already have one and we do not need that when it will be merged. for anything to ask or state do comment in the thread itself.
- Rename the names of the ".png" files to more specific one like "LOGIN.png" or "HOME.png".
- Kindly resize the images if possible.

**Comment by malakar-swastik** [comment]
Okay sure.

**Comment by neil-dev** [comment]
@malakar-swastik keep the authentication and login files and remove the rest as they are in conflict with the vision of our app. Also, can you add just the logo separately?

**Comment by malakar-swastik** [comment]
Okay sure.

**Comment by neil-dev** [comment]
@malakar-swastik I have merged your PR, however, a small change has to be made. In login.png, remove "Create Account? Sign up" line and change "login button" to "Signin". 
In the authentication.png file add a "Verify" button below the text field. Also change the text field to six separate boxes, each for one OTP digit.
Make these changes and create a new PR.

**Comment by malakar-swastik** [comment]
Cool. Will do.

**Pull request merged**
