### PR TITLE
docs: update file Code Of Conduct & all its respective references (#5)

### LINKED ISSUE #5: Improve Code of Conduct

### PR DESCRIPTION
**Pull request by aniketrb-github**
# Description
- Renamed filename from `CODEOFCONDUCT.md` to `CODE_OF_CONDUCT.md`
- Updated the file content so that any individual can refer and adhere to the guidelines and can avoid violating any of them.
- Updated the reference link in `README.md`
- Updated the reference link in `CONTRIBUTING.md`

Fixes #5 

# Type of Change:
- Documentation

# How has this been tested?
`Before the Code changes were made:`
before-changes

`After the Code changes were made:`
after-changes

# Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by aniketrb-github** [comment]
Hi @Anushka-shukla ,
1) Please review the PR for [this issue](https://github.com/neil-dev/YouSafe/issues/5).

2) Also Anushka here I have made an attempt to introduce a **Pull Request Template** for my P.R as a trial.
Let me know your thoughts about the PR template.

Thanks.

**Review by neil-dev — APPROVED** [review]
It looks good.

**Comment by aniketrb-github** [comment]
> It looks good.

Thanks. 😃

**Comment by aniketrb-github** [comment]
> It looks good.

Hi @neil-dev, 
As this repo. is tagged with hacktoberfest, a humble request of mine, Can you please go through the following link.
[Hacktoberfest Updated guidelines(2nd oct 2020).](https://hacktoberfest.digitalocean.com/hacktoberfest-update?utm_medium=email&utm_source=hacktoberfest&utm_campaign=main_&utm_content=response)

In short, Can you please label my completed [pull request-1](https://github.com/neil-dev/YouSafe/pull/21) and [pull request-2](https://github.com/neil-dev/YouSafe/pull/18) as `hacktoberfest-accepted` just to align with above guidelines
Thank you. :)

**Comment by imanishbarnwal** [comment]
> > It looks good.
> 
> Hi @neil-dev,
> As this repo. is tagged with hacktoberfest, a humble request of mine, Can you please go through the following link.
> [Hacktoberfest Updated guidelines(2nd OCT 2020).](https://hacktoberfest.digitalocean.com/hacktoberfest-update?utm_medium=email&utm_source=hacktoberfest&utm_campaign=main_&utm_content=response)
> 
> In short, Can you please label my completed [pull request-1](https://github.com/neil-dev/YouSafe/pull/21) and [pull request-2](https://github.com/neil-dev/YouSafe/pull/18) as **`hacktoberfest-accepted`** just to align with the above guidelines
> Thank you. :)

Hey @aniketrb-github, it doesn't require if it's already merged. Plus your PR is raised on 2nd Oct. so this update is not applicable for the PR raised before 3rd Oct. So, don't worry.

**Comment by aniketrb-github** [comment]
> > > It looks good.
> > 
> > 
> > Hi @neil-dev,
> > As this repo. is tagged with hacktoberfest, a humble request of mine, Can you please go through the following link.
> > [Hacktoberfest Updated guidelines(2nd OCT 2020).](https://hacktoberfest.digitalocean.com/hacktoberfest-update?utm_medium=email&utm_source=hacktoberfest&utm_campaign=main_&utm_content=response)
> > In short, Can you please label my completed [pull request-1](https://github.com/neil-dev/YouSafe/pull/21) and [pull request-2](https://github.com/neil-dev/YouSafe/pull/18) as **`hacktoberfest-accepted`** just to align with the above guidelines
> > Thank you. :)
> 
> Hey @aniketrb-github, it doesn't require if it's already merged. Plus your PR is raised on 2nd Oct. so this update is not applicable for the PR raised before 3rd Oct. So, don't worry.

Oh okay. That's great.
Thanks for your response. :)

**Pull request merged**
